In [8]:
import numpy as np 
import sympy as sym



x, y = sym.symbols('x y')
function  = x**2 - (3/2)*x*y + y**2
partial_diff = function.diff(x)

print(partial_diff)

2*x - 1.5*y


In [10]:
import numpy as np 
import sympy as sym



x1, x2 = sym.symbols('x1 x2')
function  = x1**2 - (3/2)*x1*x2 + x2**2
partial_diff = function.diff(x1)

print(partial_diff)

2*x1 - 1.5*x2


In [12]:
import numpy as np 
import sympy as sym



x1, x2, x3 = sym.symbols('x1 x2 x3')
function  = x1**2 - (3/2)*x1*x2 + x2**2 + x3*x2*x1
partial_diff2 = function.diff(x3)

print(partial_diff2)

x1*x2


In [14]:
partial_diff3 = partial_diff2.diff(x2)
print(partial_diff3)

x1


In [22]:
import numpy as np 
import sympy as sym



x1, x2 = sym.symbols('x1 x2')
function  = x1**2 - (3/2)*x1*x2 + x2**2
partial_diff1 = function.diff(x1)
partial_diff2 = function.diff(x2)
print(partial_diff)

gradient = np.array([
    [partial_diff1, partial_diff2]
])

print(gradient.shape)
print(gradient[0])

2*x1 - 1.5*x2
(1, 2)
[2*x1 - 1.5*x2 -1.5*x1 + 2*x2]


In [26]:
def hei(x):
    lol = x+2
    lol2 = x+4
    return lol, lol2 

hei(3)[0]

5

In [29]:
import numpy as np 
import sympy as sym



x1, x2 = sym.symbols('x1 x2')
function  = x1**2 - (3/2)*x1*x2 + x2**2
partial_diff = function.diff(x1)

print(partial_diff)
partial_diff.evalf(subs={x1: 2, x2: 4})

2*x1 - 1.5*x2


-2.00000000000000

In [36]:
def gradientandHessian(sp1, sp2):
    x1, x2 = sym.symbols('x1 x2')
    function = x1**2 - (3/2)*x1*x2 + x2**2
    der_x1 = function.diff(x1)
    der_x2 = function.diff(x2)
    
    gradient = np.array([
        [der_x1, der_x2]
    ])
    
    der_x1x1 = der_x1.diff(x1)
    der_x2x2 = der_x2.diff(x2)
    der_cross = der_x1.diff(x2)
    
    hessian = np.array([
        [der_x1x1, der_cross],
        [der_cross, der_x2x2]
    ])
    return gradient, hessian, x

gradientandHessian(3,3)[0]

array([[2*x1 - 1.5*x2, -1.5*x1 + 2*x2]], dtype=object)

In [40]:
x1, x2 = sym.symbols('x1 x2')
function = x1**2 - (3/2)*x1*x2 + x2**2
der_x1 = function.diff(x1)
der_x2 = function.diff(x2)

der_x1_values = function.diff(x1).evalf(subs={x1: 2, x2: 4})
der_x2_values = function.diff(x2).evalf(subs={x1: 2, x2: 4})

gradient = np.array([
    [der_x1, der_x2]
])

gradient_values = np.array([
    [der_x1_values, der_x2_values]
])

der_x1x1 = der_x1.diff(x1)
der_x2x2 = der_x2.diff(x2)
der_cross = der_x1.diff(x2)

der_x1x1_values = der_x1.diff(x1).evalf(subs={x1: 2, x2: 4})
der_x2x2_values = der_x2.diff(x2)
der_cross_values = der_x1.diff(x2)

hessian = np.array([
    [der_x1x1, der_cross],
    [der_cross, der_x2x2]
])
    
print(gradient)
print("--")
print(hessian)
print("values..")
print(gradient_values)
    

[[2*x1 - 1.5*x2 -1.5*x1 + 2*x2]]
--
[[2 -1.50000000000000]
 [-1.50000000000000 2]]
values..
[[-2.00000000000000 5.00000000000000]]
